In [8]:
import pandas as pd
import numpy as np

# Import des datas

In [2]:
file_path = 'data_qg.xlsx'

sheet_names = [
    'T10', 'T1', 'SP', 'IP', 'Emply',
    'Exptn', 'Exptn1', 'PI', 'LEI',
    'Manu', 'Manu1', 'Oil'
]


dfs = {
    name: pd.read_excel(file_path, sheet_name=name)
    for name in sheet_names
}

for name, df in dfs.items():
    df['Date'] = pd.to_datetime(df['Date'])
    value_col = df.columns[1]
    df = df.rename(columns={value_col: name})
    df = df.set_index('Date')
    dfs[name] = df[[name]]

data = pd.concat(dfs.values(), axis=1)
data = data.sort_index()
data['TERM'] = data['T10'] - data['T1']
data

,T10,T1,SP,IP,Emply,Exptn,Exptn1,PI,LEI,Manu,Manu1,Oil,TERM
Date,,,,,,,,,,,,,
1919-01-01,NaN,NaN,NaN,4.8739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-02-01,NaN,NaN,NaN,4.6585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-03-01,NaN,NaN,NaN,4.5238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-04-01,NaN,NaN,NaN,4.6046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-05-01,NaN,NaN,NaN,4.6315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-02,4.19,3.47,6858.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.72
2026-01-05,4.17,3.47,6902.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70
2026-01-06,4.18,3.48,6944.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70
2026-01-07,NaN,NaN,6920.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-01-08,NaN,NaN,6911.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data['Manu_final'] = data['Manu'].combine_first(data['Manu1'])

data = data.drop(columns=['Manu', 'Manu1'])
data = data.rename(columns={'Manu_final': 'Manu'})
data

,T10,T1,SP,IP,Emply,Exptn,Exptn1,PI,LEI,Oil,TERM,Manu
Date,,,,,,,,,,,,
1919-01-01,NaN,NaN,NaN,4.8739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-02-01,NaN,NaN,NaN,4.6585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-03-01,NaN,NaN,NaN,4.5238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-04-01,NaN,NaN,NaN,4.6046,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919-05-01,NaN,NaN,NaN,4.6315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-02,4.19,3.47,6858.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.72,NaN
2026-01-05,4.17,3.47,6902.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-06,4.18,3.48,6944.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-07,NaN,NaN,6920.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-01-08,NaN,NaN,6911.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data = data[data.index >= '1959-01-01']
data

,T10,T1,SP,IP,Emply,Exptn,Exptn1,PI,LEI,Oil,TERM,Manu
Date,,,,,,,,,,,,
1959-01-01,NaN,NaN,NaN,21.9998,52478.0,NaN,NaN,2426.0,100.0065,3.0,NaN,NaN
1959-01-02,NaN,NaN,55.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-05,NaN,NaN,55.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-06,NaN,NaN,55.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-07,NaN,NaN,54.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-02,4.19,3.47,6858.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.72,NaN
2026-01-05,4.17,3.47,6902.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-06,4.18,3.48,6944.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-07,NaN,NaN,6920.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-01-08,NaN,NaN,6911.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
rates_m = data["TERM"].copy()
rates_m = rates_m.resample('M').mean()
rates_m.index = pd.to_datetime(rates_m.index)
rates_m

/var/folders/5q/kk1fbxc906b97fnm87mtg7m80000gn/T/ipykernel_3566/1944646259.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  rates_m = rates_m.resample('M').mean()

Date
1959-01-31         NaN
1959-02-28         NaN
1959-03-31         NaN
1959-04-30         NaN
1959-05-31         NaN
                ...
2025-09-30    0.460000
2025-10-31    0.447727
2025-11-30    0.438889
2025-12-31    0.601364
2026-01-31    0.706667
Freq: ME, Name: TERM, Length: 805, dtype: float64

In [18]:
monthly_vars = ['SP', 'IP', 'Emply', 'Emply', 'PI', 'LEI', 'Manu', 'Oil']
X_m = data[monthly_vars].copy()
X_m.index = pd.to_datetime(X_m.index)
X_m = X_m.resample('M').last()
X_m

/var/folders/5q/kk1fbxc906b97fnm87mtg7m80000gn/T/ipykernel_3566/4146081411.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  X_m = X_m.resample('M').last()

                  SP  IP  Emply  Emply  PI       LEI  Manu  Oil
Date
1959-01-31  0.003978 NaN    NaN    NaN NaN  100.0065   NaN  NaN
1959-02-28  0.001264 NaN    NaN    NaN NaN  100.3623   NaN  NaN
1959-03-31 -0.000180 NaN    NaN    NaN NaN  100.6661   NaN  NaN
1959-04-30 -0.001735 NaN    NaN    NaN NaN  100.8976   NaN  NaN
1959-05-31  0.004954 NaN    NaN    NaN NaN  101.0383   NaN  NaN
...              ...  ..    ...    ...  ..       ...   ...  ...
2025-09-30  0.004083 NaN    NaN    NaN NaN       NaN   NaN  NaN
2025-10-31  0.002614 NaN    NaN    NaN NaN       NaN   NaN  NaN
2025-11-30  0.006883 NaN    NaN    NaN NaN       NaN   NaN  NaN
2025-12-31 -0.007385 NaN    NaN    NaN NaN       NaN   NaN  NaN
2026-01-31 -0.001395 NaN    NaN    NaN NaN       NaN   NaN  NaN

[805 rows x 8 columns]

In [19]:
X_m = X_m.join(rates_m[['TERM']], how='inner')
X_m

KeyError: "None of [Index(['TERM'], dtype='object', name='Date')] are in the [index]"

## Data transformation - TABLE 6

![Table 6 – Definition of regressors](table6.png)

In [9]:
def log(x):
    return np.log(x)

def dlog(x):
    return np.log(x).diff()

In [10]:
levels_var = ['TERM', 'LEI']
log_vars = ['Exptn']
dlog_vars = ['SP', 'IP', 'Emply', 'PI', 'Manu', 'Oil']

for v in log_vars:
    data[v] = log(data[v])

for v in dlog_vars:
    data[v] = dlog(data[v])
    
data

/var/folders/5q/kk1fbxc906b97fnm87mtg7m80000gn/T/ipykernel_3566/2340207500.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[v] = log(data[v])
/var/folders/5q/kk1fbxc906b97fnm87mtg7m80000gn/T/ipykernel_3566/2340207500.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[v] = dlog(data[v])

,T10,T1,SP,IP,Emply,Exptn,Exptn1,PI,LEI,Oil,TERM,Manu
Date,,,,,,,,,,,,
1959-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0065,NaN,NaN,NaN
1959-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-05,NaN,NaN,0.003960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-06,NaN,NaN,-0.001258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1959-01-07,NaN,NaN,-0.012672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-01-02,4.19,3.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.72,NaN
2026-01-05,4.17,3.47,0.006334,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-06,4.18,3.48,0.006178,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.70,NaN
2026-01-07,NaN,NaN,-0.003446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-01-08,NaN,NaN,-0.001395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN