In [1]:
import pandas as pd

gdp = pd.read_csv("gdp_stat_norm.csv")
X   = pd.read_csv("regressors_stat_norm.csv")

# GDP trimestriel
gdp["Date"] = pd.to_datetime(gdp["Date"])
y_q = pd.Series(gdp["GDP"].values, index=gdp["Date"]).to_period("Q")

# Régressseurs mensuels
X["Date"] = pd.to_datetime(X["Date"])
X_m = X.set_index("Date")   # colonnes: SP, IP, Emply, Exptn, PI, LEI, Oil, Manu, TERM

In [2]:
from midas.runner_table7 import table7_rmse_grid

In [3]:
rmse_small_TERM = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["TERM"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_TERM

             rmse_regular  rmse_multiplicative    n
regressor h
TERM      1      0.744669             0.736135  121
          2      0.729332             0.728833  120
          3      0.800299             0.808310  119
          4      0.750735             0.750735  118
          5      0.772001             0.771723  117
          6      0.816251             0.813401  116
          7      0.774256             0.715226  115
          8      0.762909             0.758437  114

In [4]:
rmse_small_TERM.to_csv("rmse_small_TERM_table7.csv")

In [5]:
rmse_small_SP = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["SP"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_SP

             rmse_regular  rmse_multiplicative    n
regressor h
SP        1      0.691450             0.691579  121
          2      0.732502             0.713238  120
          3      0.764391             0.778450  119
          4      0.778869             0.761835  118
          5      0.795352             0.807945  117
          6      0.813886             0.798034  116
          7      0.771886             0.756947  115
          8      0.733249             0.748429  114

In [6]:
rmse_small_SP.to_csv("rmse_small_SP_table7.csv")

In [7]:
rmse_small_IP = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["IP"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_IP

             rmse_regular  rmse_multiplicative    n
regressor h
IP        1      0.710089             0.654977  121
          2      0.746852             0.749150  120
          3      0.768351             0.777618  119
          4      0.745527             0.782150  118
          5      0.795993             0.789167  117
          6      0.785535             0.752413  116
          7      0.744458             0.733230  115
          8      0.731311             0.714779  114

In [8]:
rmse_small_IP.to_csv("rmse_small_IP_table7.csv")

In [9]:
rmse_small_Emply = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["Emply"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_Emply

             rmse_regular  rmse_multiplicative    n
regressor h
Emply     1      0.705846             0.712431  121
          2      0.757235             0.761358  120
          3      0.793046             0.800492  119
          4      0.786842             0.795010  118
          5      0.800557             0.794430  117
          6      0.782893             0.788885  116
          7      0.750512             0.749233  115
          8      0.727765             0.735553  114

In [10]:
rmse_small_Emply.to_csv("rmse_small_Emply_table7.csv")

In [3]:
rmse_small_Exptn = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["Exptn"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_Exptn

ValueError: No usable training observations.

In [12]:
# rmse_small_Exptn.to_csv("rmse_small_Exptn_table7.csv")

In [13]:
rmse_small_PI = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["PI"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_PI

             rmse_regular  rmse_multiplicative    n
regressor h
PI        1      0.687859             0.696806  121
          2      0.758280             0.768630  120
          3      0.803371             0.806043  119
          4      0.825844             0.800920  118
          5      0.802831             0.823984  117
          6      0.796529             0.841986  116
          7      0.747537             0.778569  115
          8      0.762738             0.755703  114

In [14]:
rmse_small_PI.to_csv("rmse_small_PI_table7.csv")

In [15]:
rmse_small_LEI = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["LEI"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_LEI

             rmse_regular  rmse_multiplicative    n
regressor h
LEI       1      0.635246             0.634855  121
          2      0.640286             0.637452  120
          3      0.641444             0.639332  119
          4      0.631502             0.631497  118
          5      0.661815             0.637127  117
          6      0.678108             0.678108  116
          7      0.669710             0.669710  115
          8      0.677876             0.677876  114

In [16]:
rmse_small_LEI.to_csv("rmse_small_LEI_table7.csv")

In [17]:
rmse_small_Manu = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["Manu"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_Manu

             rmse_regular  rmse_multiplicative    n
regressor h
Manu      1      0.725967             0.746953  121
          2      0.752186             0.801501  120
          3      0.808411             0.798001  119
          4      0.768068             0.802567  118
          5      0.788011             0.790641  117
          6      0.807391             0.849361  116
          7      0.737750             0.791154  115
          8      0.796556             0.753086  114

In [18]:
rmse_small_Manu.to_csv("rmse_small_Manu_table7.csv")

In [4]:
rmse_small_Oil = table7_rmse_grid(
    y_q=y_q,
    X=X_m,
    horizons=range(1, 9),
    regressors=["Oil"],
    Kx_LF=6, m=3, j_obs=2,
    train_end0="1978Q4",
    eval_start="1979Q1",
    eval_end="2009Q1",
    warm_start=True,
    maxiter=100,
)
rmse_small_Oil

             rmse_regular  rmse_multiplicative    n
regressor h
Oil       1      0.730839             0.728793  121
          2      0.756888             0.764261  120
          3      0.806989             0.822018  119
          4      0.785689             0.812413  118
          5      0.812205             0.946659  117
          6      0.785288             0.893814  116
          7      0.806930             0.736058  115
          8      0.781708             0.734953  114

In [5]:
rmse_small_Oil.to_csv("rmse_small_Oil_table7.csv")