In [2]:
import pandas as pd

panel_A_h1_midas = pd.read_excel("Table_4A_PanelA_MIDAS.xlsx", index_col=0)
panel_A_h1_adl = pd.read_excel("Table_4A_PanelA_Multiplicative_MIDAS.xlsx", index_col=0)

panel_B_h4_midas = pd.read_excel("Table_4A_PanelB_MIDAS.xlsx", index_col=0)
panel_B_h4_adl = pd.read_excel("Table_4A_PanelB_Multiplicative_MIDAS.xlsx", index_col=0)

panel_C_h1_midas = pd.read_excel("Table_4B_PanelC_MIDAS.xlsx", index_col=0)
panel_C_h1_adl = pd.read_excel("Table_4B_PanelC_Multiplicative_MIDAS.xlsx", index_col=0)

panel_D_h4_midas = pd.read_excel("Table_4B_PanelD_MIDAS.xlsx", index_col=0)
panel_D_h4_adl = pd.read_excel("Table_4B_PanelD_Multiplicative_MIDAS.xlsx", index_col=0)

In [10]:
panel_A = pd.concat(
    [
        panel_A_h1_midas,   # shape (5,4)
        panel_A_h1_adl,
        panel_B_h4_midas,
        panel_B_h4_adl
    ],
    axis=1,
    keys=[
        "Regular MIDAS",
        "Multiplicative MIDAS",
        "Regular MIDAS",
        "Multiplicative MIDAS"
    ]
)
panel_A = panel_A.round(3)

panel_A

      Regular MIDAS                      Multiplicative MIDAS                \
              -0.90  -0.50   0.50   0.95                -0.90  -0.50   0.50
-0.90         1.049  1.050  1.039  0.915                1.073  1.087  1.055
-0.50         1.047  1.123  1.129  1.021                1.061  1.150  1.138
 0.00         1.043  1.122  1.125  1.037                1.066  1.149  1.128
 0.50         1.033  1.116  1.115  1.048                1.043  1.136  1.125
 0.95         0.956  1.054  1.082  1.080                0.953  1.036  1.068

             Regular MIDAS                      Multiplicative MIDAS         \
        0.95         -0.90  -0.50   0.50   0.95                -0.90  -0.50
-0.90  0.914         1.120  1.104  1.101  1.152                1.127  1.127
-0.50  1.022         1.087  1.114  1.118  1.228                1.102  1.132
 0.00  1.039         1.080  1.115  1.132  1.234                1.101  1.134
 0.50  1.042         1.084  1.122  1.134  1.239                1.097  1.140
 0.95  1.067         1.190  1.288  1.296  1.313                1.142  1.194


        0.50   0.95
-0.90  1.111  1.128
-0.50  1.145  1.165
 0.00  1.150  1.159
 0.50  1.144  1.155
 0.95  1.203  1.195

In [11]:
latex_panel_A = panel_A.to_latex(
    float_format="%.2f",
    multicolumn=True,
    multirow=True,
    escape=False
)
print(latex_panel_A)

\begin{tabular}{lrrrrrrrrrrrrrrrr}
\toprule
 & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} \\
 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 \\
\midrule
-0.900000 & 1.05 & 1.05 & 1.04 & 0.92 & 1.07 & 1.09 & 1.05 & 0.91 & 1.12 & 1.10 & 1.10 & 1.15 & 1.13 & 1.13 & 1.11 & 1.13 \\
-0.500000 & 1.05 & 1.12 & 1.13 & 1.02 & 1.06 & 1.15 & 1.14 & 1.02 & 1.09 & 1.11 & 1.12 & 1.23 & 1.10 & 1.13 & 1.15 & 1.17 \\
0.000000 & 1.04 & 1.12 & 1.12 & 1.04 & 1.07 & 1.15 & 1.13 & 1.04 & 1.08 & 1.11 & 1.13 & 1.23 & 1.10 & 1.13 & 1.15 & 1.16 \\
0.500000 & 1.03 & 1.12 & 1.11 & 1.05 & 1.04 & 1.14 & 1.12 & 1.04 & 1.08 & 1.12 & 1.13 & 1.24 & 1.10 & 1.14 & 1.14 & 1.16 \\
0.950000 & 0.96 & 1.05 & 1.08 & 1.08 & 0.95 & 1.04 & 1.07 & 1.07 & 1.19 & 1.29 & 1.30 & 1.31 & 1.14 & 1.19 & 1.20 & 1.20 \\
\bottomrule
\end{tabular}

In [12]:
panel_B = pd.concat(
    [
        panel_C_h1_midas,   # shape (5,4)
        panel_C_h1_adl,
        panel_D_h4_midas,
        panel_D_h4_adl
    ],
    axis=1,
    keys=[
        "Regular MIDAS",
        "Multiplicative MIDAS",
        "Regular MIDAS",
        "Multiplicative MIDAS"
    ]
)
panel_B = panel_B.round(3)

panel_B

      Regular MIDAS                      Multiplicative MIDAS                \
              -0.90  -0.50   0.50   0.95                -0.90  -0.50   0.50
-0.90         0.919  0.967  0.981  1.472                0.919  0.968  0.985
-0.50         0.991  1.032  1.042  1.186                0.977  1.042  1.044
 0.00         1.061  1.038  1.038  1.114                1.055  1.048  1.044
 0.50         1.070  1.043  1.047  1.090                1.061  1.046  1.041
 0.95         1.257  1.088  1.079  1.071                1.227  1.065  1.062

             Regular MIDAS                      Multiplicative MIDAS         \
        0.95         -0.90  -0.50   0.50   0.95                -0.90  -0.50
-0.90  1.509         1.127  1.149  1.147  1.280                1.121  1.144
-0.50  1.186         1.139  1.180  1.195  1.311                1.130  1.171
 0.00  1.117         1.136  1.183  1.192  1.298                1.136  1.166
 0.50  1.090         1.145  1.187  1.197  1.298                1.125  1.154
 0.95  1.061         1.257  1.270  1.289  1.322                1.200  1.187


        0.50   0.95
-0.90  1.145  1.252
-0.50  1.165  1.241
 0.00  1.169  1.227
 0.50  1.167  1.224
 0.95  1.192  1.196

In [13]:
latex_panel_B = panel_B.to_latex(
    float_format="%.2f",
    multicolumn=True,
    multirow=True,
    escape=False
)
print(latex_panel_B)

\begin{tabular}{lrrrrrrrrrrrrrrrr}
\toprule
 & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} \\
 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 \\
\midrule
-0.900000 & 0.92 & 0.97 & 0.98 & 1.47 & 0.92 & 0.97 & 0.98 & 1.51 & 1.13 & 1.15 & 1.15 & 1.28 & 1.12 & 1.14 & 1.15 & 1.25 \\
-0.500000 & 0.99 & 1.03 & 1.04 & 1.19 & 0.98 & 1.04 & 1.04 & 1.19 & 1.14 & 1.18 & 1.20 & 1.31 & 1.13 & 1.17 & 1.17 & 1.24 \\
0.000000 & 1.06 & 1.04 & 1.04 & 1.11 & 1.05 & 1.05 & 1.04 & 1.12 & 1.14 & 1.18 & 1.19 & 1.30 & 1.14 & 1.17 & 1.17 & 1.23 \\
0.500000 & 1.07 & 1.04 & 1.05 & 1.09 & 1.06 & 1.05 & 1.04 & 1.09 & 1.15 & 1.19 & 1.20 & 1.30 & 1.12 & 1.15 & 1.17 & 1.22 \\
0.950000 & 1.26 & 1.09 & 1.08 & 1.07 & 1.23 & 1.06 & 1.06 & 1.06 & 1.26 & 1.27 & 1.29 & 1.32 & 1.20 & 1.19 & 1.19 & 1.20 \\
\bottomrule
\end{tabular}

In [14]:
panel_A_h1_midas = pd.read_excel("Table_5_PanelA_MIDAS.xlsx", index_col=0)
panel_A_h1_adl = pd.read_excel("Table_5_PanelA_Multiplicative_MIDAS.xlsx", index_col=0)

panel_B_h4_midas = pd.read_excel("Table_5_PanelB_MIDAS.xlsx", index_col=0)
panel_B_h4_adl = pd.read_excel("Table_5_PanelB_Multiplicative_MIDAS.xlsx", index_col=0)

panel_C_h1_midas = pd.read_excel("Table_5_PanelC_MIDAS.xlsx", index_col=0)
panel_C_h1_adl = pd.read_excel("Table_5_PanelC_Multiplicative_MIDAS.xlsx", index_col=0)

panel_D_h4_midas = pd.read_excel("Table_5_PanelD_MIDAS.xlsx", index_col=0)
panel_D_h4_adl = pd.read_excel("Table_5_PanelD_Multiplicative_MIDAS.xlsx", index_col=0)

In [ ]:
panel_C = pd.concat(
    [
        panel_A_h1_midas,   # shape (5,4)
        panel_A_h1_adl,
        panel_B_h4_midas,
        panel_B_h4_adl
    ],
    axis=1,
    keys=[
        "Regular MIDAS",
        "Multiplicative MIDAS",
        "Regular MIDAS",
        "Multiplicative MIDAS"
    ]
)
panel_C = panel_C.round(3)

panel_C

      Regular MIDAS                      Multiplicative MIDAS                \
              -0.90  -0.50   0.50   0.95                -0.90  -0.50   0.50
-0.90         1.120  1.104  1.101  1.152                1.127  1.127  1.111
-0.50         1.087  1.114  1.118  1.228                1.102  1.132  1.145
 0.00         1.080  1.115  1.132  1.234                1.101  1.134  1.150
 0.50         1.084  1.122  1.134  1.239                1.097  1.140  1.144
 0.95         1.190  1.288  1.296  1.313                1.142  1.194  1.203

             Regular MIDAS                      Multiplicative MIDAS         \
        0.95         -0.90  -0.50   0.50   0.95                -0.90  -0.50
-0.90  1.128         1.120  1.104  1.101  1.152                1.127  1.127
-0.50  1.165         1.087  1.114  1.118  1.228                1.102  1.132
 0.00  1.159         1.080  1.115  1.132  1.234                1.101  1.134
 0.50  1.155         1.084  1.122  1.134  1.239                1.097  1.140
 0.95  1.195         1.190  1.288  1.296  1.313                1.142  1.194


        0.50   0.95
-0.90  1.111  1.128
-0.50  1.145  1.165
 0.00  1.150  1.159
 0.50  1.144  1.155
 0.95  1.203  1.195

In [18]:
latex_panel_c = panel_C.to_latex(
    float_format="%.2f",
    multicolumn=True,
    multirow=True,
    escape=False
)
print(latex_panel_c)

\begin{tabular}{lrrrrrrrrrrrrrrrr}
\toprule
 & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} & \multicolumn{4}{r}{Regular MIDAS} & \multicolumn{4}{r}{Multiplicative MIDAS} \\
 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 & -0.900000 & -0.500000 & 0.500000 & 0.950000 \\
\midrule
-0.900000 & 1.12 & 1.10 & 1.10 & 1.15 & 1.13 & 1.13 & 1.11 & 1.13 & 1.12 & 1.10 & 1.10 & 1.15 & 1.13 & 1.13 & 1.11 & 1.13 \\
-0.500000 & 1.09 & 1.11 & 1.12 & 1.23 & 1.10 & 1.13 & 1.15 & 1.17 & 1.09 & 1.11 & 1.12 & 1.23 & 1.10 & 1.13 & 1.15 & 1.17 \\
0.000000 & 1.08 & 1.11 & 1.13 & 1.23 & 1.10 & 1.13 & 1.15 & 1.16 & 1.08 & 1.11 & 1.13 & 1.23 & 1.10 & 1.13 & 1.15 & 1.16 \\
0.500000 & 1.08 & 1.12 & 1.13 & 1.24 & 1.10 & 1.14 & 1.14 & 1.16 & 1.08 & 1.12 & 1.13 & 1.24 & 1.10 & 1.14 & 1.14 & 1.16 \\
0.950000 & 1.19 & 1.29 & 1.30 & 1.31 & 1.14 & 1.19 & 1.20 & 1.20 & 1.19 & 1.29 & 1.30 & 1.31 & 1.14 & 1.19 & 1.20 & 1.20 \\
\bottomrule
\end{tabular}

In [ ]:
panel_D = pd.concat(
    [
        panel_C_h1_midas,   # shape (5,4)
        panel_C_h1_adl,
        panel_D_h4_midas,
        panel_D_h4_adl
    ],
    axis=1,
    keys=[
        "Regular MIDAS",
        "Multiplicative MIDAS",
        "Regular MIDAS",
        "Multiplicative MIDAS"
    ]
)
panel_D = panel_D.round(3)

panel_D

In [ ]:
latex_panel_D = panel_D.to_latex(
    float_format="%.2f",
    multicolumn=True,
    multirow=True,
    escape=False
)
print(latex_panel_D)